# Generated by Django 5.1.5 on 2025-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_phone_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
