# Generated by Django 5.1.5 on 2025-02-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_phone_number',
        ),
    ]
